spring.application.name=saga

# --- CONFIGURACIÓN POSTGRESQL ---
# Asegúrate de haber creado la base de datos 'saga_db' en tu Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/saga_db
spring.datasource.username=postgres
spring.datasource.password=2048
spring.datasource.driverClassName=org.postgresql.Driver

# Dialecto para que Hibernate hable "Postgres" correctamente
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- TUS CONFIGURACIONES DE ERRORES (Mantenlas igual) ---
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true
spring.mvc.problemdetails.enabled=false

# Mostrar el SQL en consola (útil para ver si las tablas se crean bien)
spring.jpa.show-sql=true

